### ISSUE TITLE
Bugs with multiple gpu training on lidar pointpillar with train_ddp.py

### ISSUE THREAD

**Issue by rwang5203** [yifanlu0227/CoAlign#23]
Again, tried `CUDA_VISIBLE_DEVICES=1,2,3,4,5 python -m torch.distributed.launch  --nproc_per_node=5 --use_env opencood/tools/train_ddp.py -y opencood/hypes_yaml/opv2v/lidar_only_with_noise/coalign/pointpillar_coalign_woba.yaml`
And the following error appeared:
```
Traceback (most recent call last):
  File "opencood/tools/train_ddp.py", line 250, in <module>
    main()
  File "opencood/tools/train_ddp.py", line 148, in main
    ouput_dict = model(batch_data['ego'])
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//Projects/CoAlign/opencood/models/point_pillar_baseline_multiscale.py", line 103, in forward
    batch_dict = self.pillar_vfe(batch_dict)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//Projects/CoAlign/opencood/models/sub_modules/pillar_vfe.py", line 151, in forward
    features = pfn(features)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//Projects/CoAlign/opencood/models/sub_modules/pillar_vfe.py", line 37, in forward
    for num_part in range(num_parts + 1)]
  File "/home//Projects/CoAlign/opencood/models/sub_modules/pillar_vfe.py", line 37, in <listcomp>
    for num_part in range(num_parts + 1)]
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

```

What could be the issue here? Any solutions recommended? This seems to be bugs with `train_ddp.py`.

**Comment by yifanlu0227** [comment]
Sorry but it works well on my machine. And many people can train_ddp.py successfully. I will open this issue, if anyone encounters the same problem you can discuss it.

**Comment by DOUDOUZXL** [comment]
> 再次尝试，`CUDA_VISIBLE_DEVICES=1,2,3,4,5 python -m torch.distributed.launch --nproc_per_node=5 --use_env opencood/tools/train_ddp.py -y opencood/hypes_yaml/opv2v/lidar_only_with_noise/coalign/pointpillar_coalign_woba.yaml` 出现以下错误：
> 
> ```
> Traceback (most recent call last):
>   File "opencood/tools/train_ddp.py", line 250, in <module>
>     main()
>   File "opencood/tools/train_ddp.py", line 148, in main
>     ouput_dict = model(batch_data['ego'])
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
>     output = self.module(*inputs[0], **kwargs[0])
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home//Projects/CoAlign/opencood/models/point_pillar_baseline_multiscale.py", line 103, in forward
>     batch_dict = self.pillar_vfe(batch_dict)
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home//Projects/CoAlign/opencood/models/sub_modules/pillar_vfe.py", line 151, in forward
>     features = pfn(features)
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home//Projects/CoAlign/opencood/models/sub_modules/pillar_vfe.py", line 37, in forward
>     for num_part in range(num_parts + 1)]
>   File "/home//Projects/CoAlign/opencood/models/sub_modules/pillar_vfe.py", line 37, in <listcomp>
>     for num_part in range(num_parts + 1)]
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
>     return torch._C._nn.linear(input, weight, bias)
> RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
> ```
> 
> 这里可能存在什么问题？有什么建议的解决方案吗？这似乎是 的错误`train_ddp.py`。

我在单卡时训练时遇到这个问题，后来具体的原因我已经忘记，但是我明确记得，我重装了适配版本的CUDA和cudnn解决了此问题，我记得我当时是由GPT编写了简单的测试程序，最终解决了这个erro，复现DAIR-V2X项目时出现此类问题
